### ISSUE TITLE
Build slide deck for training attendees on Traits, TraitsUI and Pyface

### ISSUE THREAD

**Issue by jonathanrocher** [jonathanrocher/ets_tutorial#19]
- Update existing content to use models/classes from the tutorial 
- Choose and implement a format that we move to (pptx has issues): jupytext? google slide?

**Comment by siddhantwahal** [comment]
These look pretty nice too, the mechanism might be similar to md/jupytext:
https://github.com/mwouts/jupytext_pyparis_2018/blob/master/slides/Jupytext.Rmd
